# 4.3 - Selecting Data in a DataFrame

Practice Lab: Selecting data in a Dataframe

## Tujuan
- Memahami struktur DataFrame dan Series di Pandas
- Memilih kolom, baris, dan cell tertentu menggunakan `loc()` dan `iloc()`
- Melakukan slicing pada DataFrame

In [1]:
import pandas as pd

In [2]:
# Dictionary sebagai data mentah
x = {
    'Name': ['Rose', 'John', 'Jane', 'Mary'],
    'ID': [1, 2, 3, 4],
    'Department': ['Architect Group', 'Software Group', 'Design Team', 'Infrastructure'],
    'Salary': [100000, 80000, 50000, 60000]
}

# ubah dictionary jadi DataFrame -> keys jadi nama kolom, values jadi isi baris
df = pd.DataFrame(x)
df

   Name  ID       Department  Salary
0  Rose   1  Architect Group  100000
1  John   2   Software Group   80000
2  Jane   3      Design Team   50000
3  Mary   4   Infrastructure   60000

In [3]:
# Ambil kolom "ID" -> pakai DOUBLE bracket [[...]] supaya hasilnya tetap DataFrame
x = df[['ID']]
x

   ID
0   1
1   2
2   3
3   4

In [4]:
type(x)

pandas.DataFrame

In [5]:
# Ambil 3 kolom: Department, Salary, ID (urutan bebas, tidak harus sama seperti df asli)
z = df[['Department', 'Salary', 'ID']]
z

        Department  Salary  ID
0  Architect Group  100000   1
1   Software Group   80000   2
2      Design Team   50000   3
3   Infrastructure   60000   4

## Try It Yourself

### Problem 1: Buat DataFrame data mahasiswa
### Problem 2: Ambil kolom Marks
### Problem 3: Ambil kolom Country dan Course

In [6]:
a = {
    'Student': ['David', 'Samuel', 'Terry', 'Evan'],
    'Age': ['27', '24', '22', '32'],
    'Country': ['UK', 'Canada', 'China', 'USA'],
    'Course': ['Python', 'Data Structures', 'Machine Learning', 'Web Development'],
    'Marks': ['85', '72', '89', '76']
}
df1 = pd.DataFrame(a)
df1

  Student Age Country            Course Marks
0   David  27      UK            Python    85
1  Samuel  24  Canada   Data Structures    72
2   Terry  22   China  Machine Learning    89
3    Evan  32     USA   Web Development    76

In [7]:
b = df1[['Marks']]
b

  Marks
0    85
1    72
2    89
3    76

In [8]:
c = df1[['Country', 'Course']]
c

  Country            Course
0      UK            Python
1  Canada   Data Structures
2   China  Machine Learning
3     USA   Web Development

In [9]:
# 1 kurung siku -> hasilnya Series, bukan DataFrame
x = df1['Student']
x

0     David
1    Samuel
2     Terry
3      Evan
Name: Student, dtype: str

In [10]:
type(x)

pandas.Series

## Exercise 2: loc() dan iloc()

- `iloc[row, col]` — akses berdasarkan **posisi angka**
- `loc[row, col]` — akses berdasarkan **nama/label**

In [11]:
# Baris pertama (index 0), kolom pertama (index 0)
df.iloc[0, 0]

'Rose'

In [12]:
# Baris pertama, kolom ketiga (index 2)
df.iloc[0, 2]

'Architect Group'

In [13]:
# Baris dengan index 0, kolom bernama 'Salary'
df.loc[0, 'Salary']

np.int64(100000)

In [14]:
# Buat DataFrame baru df2, set kolom "Name" jadi index
df2 = df
df2 = df2.set_index("Name")

In [15]:
df2.head()

      ID       Department  Salary
Name
Rose   1  Architect Group  100000
John   2   Software Group   80000
Jane   3      Design Team   50000
Mary   4   Infrastructure   60000

In [16]:
# Sekarang index-nya nama orang, bukan angka
df2.loc['Jane', 'Salary']

np.int64(50000)

## Try It Yourself

Gunakan `df2` untuk:
1. Cari Department milik Jane pakai `loc()`
2. Cari Salary milik Mary pakai `iloc()`

In [17]:
df2.loc['Jane', 'Department']

'Design Team'

In [18]:
# Mary ada di baris index ke-3 (Rose=0, John=1, Jane=2, Mary=3), Salary di kolom ke-2
df2.iloc[3, 2]

np.int64(60000)

## Exercise 3: Slicing

Perhatikan: `iloc` slicing TIDAK termasuk batas akhir, tapi `loc` slicing TERMASUK batas akhir.

In [19]:
# baris index 0-1 (2 tidak termasuk), kolom index 0-2 (3 tidak termasuk)
df.iloc[0:2, 0:3]

   Name  ID       Department
0  Rose   1  Architect Group
1  John   2   Software Group

In [20]:
# baris index 0 SAMPAI 2 (termasuk 2!), kolom 'ID' sampai 'Department' (termasuk)
df.loc[0:2, 'ID':'Department']

   ID       Department
0   1  Architect Group
1   2   Software Group
2   3      Design Team

In [21]:
# baris 'Rose' sampai 'Jane' (termasuk Jane), kolom 'ID' sampai 'Department'
df2.loc['Rose':'Jane', 'ID':'Department']

      ID       Department
Name
Rose   1  Architect Group
John   2   Software Group
Jane   3      Design Team

## Try It Yourself

Gunakan `loc()` pada `df` untuk slicing Name, ID, dan Department dengan index 2 sampai 3.

In [22]:
df.loc[2:3, 'Name':'Department']

   Name  ID      Department
2  Jane   3     Design Team
3  Mary   4  Infrastructure